### ISSUE TITLE
Still missing some line numbers

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolinkml#100]
Running the make file against biolink-model (tag biolink_issue) gives the following error:

```
======================================================================
ERROR: test_biolinkmodel (tests.test_pythongen.PythonGenTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/solbrig/git/biolink/biolink-model/tests/test_pythongen.py", line 23, in test_biolinkmodel
    self.gen_and_comp_python(BIOLINK_MODEL_YAML)
  File "/Users/solbrig/git/biolink/biolink-model/tests/test_pythongen.py", line 20, in gen_and_comp_python
    exec(spec, module.__dict__)
  File "test", line 608, in <module>
NameError: name 'DiseaseToThingAssociationId' is not defined

----------------------------------------------------------------------
```

**Comment by jiaola** [comment]
Find the biolink-model file here: https://github.com/biolink/biolink-model/releases/tag/biolink_issue
