### ISSUE TITLE
test_meta_owl fails

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#139]
```turtle
***** New graph saved in /Users/cjm/repos/biolinkml/tests/target/meta.owl *****
----- Expected graph -----

meta:abstract a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:alias a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:aliases a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:alt_description_source a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:alt_description_text a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:alt_descriptions a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:apply_to a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:class_definition_apply_to a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:class_definition_is_a a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:class_definition_mixins a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:class_uri a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:classes a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:close_mappings a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:comments a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:default_curi_maps a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:default_prefix a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:default_range a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:definition_uri a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:deprecated a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:deprecated_element_has_exact_replacement a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:deprecated_element_has_possible_replacement a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:description a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:emit_prefixes a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:exact_mappings a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:examples a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:from_schema a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:generation_date a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:id a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:id_prefixes a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:imported_from a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:imports a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:in_subset a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:inverse a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:is_a a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:is_class_field a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:is_usage_slot a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:license a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:local_name_source a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:local_name_value a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:local_names a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:mappings a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:metamodel_version a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:mixin a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:mixins a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:name a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:notes a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:owner a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:prefix_prefix a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:prefix_reference a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:prefixes a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:related_mappings a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:see_also a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:singular_name a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:slot_definition_apply_to a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:slot_definition_is_a a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:slot_definition_mixins a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:slot_definitions a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:slot_uri a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:slot_usage a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:slots a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:source_file a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:source_file_date a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:source_file_size a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:subclass_of a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:subproperty_of a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:subsets a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:symmetric a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:title a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:todos a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:typeof a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:types a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:union_of a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:value a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:value_description a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:values_from a <http://www.w3.org/2002/07/owl#AnnotationProperty> .

meta:version a <http://www.w3.org/2002/07/owl#AnnotationProperty> .


----- Actual Graph -----

meta:Element rdfs:subClassOf [ a ns1:Restriction ;
            ns1:allValuesFrom meta:uriorcurie ;
            ns1:onProperty meta:mappings ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:uriorcurie ;
            ns1:onProperty meta:exact_mappings ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:uriorcurie ;
            ns1:onProperty meta:deprecated_element_has_exact_replacement ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:uriorcurie ;
            ns1:onProperty meta:see_also ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:uriorcurie ;
            ns1:onProperty meta:related_mappings ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:uriorcurie ;
            ns1:onProperty meta:close_mappings ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:string ;
            ns1:onProperty meta:todos ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:AltDescription ;
            ns1:onProperty meta:alt_descriptions ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:Example ;
            ns1:onProperty meta:examples ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:SubsetDefinition ;
            ns1:onProperty meta:in_subset ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:uriorcurie ;
            ns1:onProperty meta:definition_uri ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:uriorcurie ;
            ns1:onProperty meta:deprecated_element_has_possible_replacement ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:uri ;
            ns1:onProperty meta:from_schema ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:string ;
            ns1:onProperty meta:comments ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:deprecated ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:LocalName ;
            ns1:onProperty meta:local_names ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:imported_from ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:description ],
        [ a ns1:Restriction ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:name ;
            ns1:qualifiedCardinality 1 ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:string ;
            ns1:onProperty meta:aliases ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:ncname ;
            ns1:onProperty meta:id_prefixes ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:string ;
            ns1:onProperty meta:notes ] .

meta:SchemaDefinition rdfs:subClassOf [ a ns1:Restriction ;
            ns1:allValuesFrom meta:TypeDefinition ;
            ns1:onProperty meta:types ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:ClassDefinition ;
            ns1:onProperty meta:classes ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:SubsetDefinition ;
            ns1:onProperty meta:subsets ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:uriorcurie ;
            ns1:onProperty meta:imports ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:SlotDefinition ;
            ns1:onProperty meta:slots ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:string ;
            ns1:onProperty meta:default_curi_maps ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:version ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:integer ;
            ns1:onProperty meta:source_file_size ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:license ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:ncname ;
            ns1:onProperty meta:emit_prefixes ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:TypeDefinition ;
            ns1:onProperty meta:default_range ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:Prefix ;
            ns1:onProperty meta:prefixes ],
        [ a ns1:Restriction ;
            ns1:onClass meta:uri ;
            ns1:onProperty meta:id ;
            ns1:qualifiedCardinality 1 ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:source_file ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:datetime ;
            ns1:onProperty meta:source_file_date ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:title ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:default_prefix ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:datetime ;
            ns1:onProperty meta:generation_date ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:metamodel_version ] .

meta:alt_description_source a ns1:ObjectProperty .

meta:alt_description_text a ns1:ObjectProperty .

meta:class_definition_apply_to a ns1:ObjectProperty .

meta:class_definition_is_a a ns1:ObjectProperty .

meta:class_definition_mixins a ns1:ObjectProperty .

meta:slot_definition_apply_to a ns1:ObjectProperty .

meta:slot_definition_is_a a ns1:ObjectProperty .

meta:slot_definition_mixins a ns1:ObjectProperty .

meta:slot_definitions a ns1:ObjectProperty .

meta:value_description a ns1:ObjectProperty .

meta:AltDescription rdfs:subClassOf [ a ns1:Restriction ;
            ns1:onClass meta:ncname ;
            ns1:onProperty meta:source ;
            ns1:qualifiedCardinality 1 ],
        [ a ns1:Restriction ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:description ;
            ns1:qualifiedCardinality 1 ] .

meta:Example rdfs:subClassOf [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:value ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:description ] .

meta:LocalName rdfs:subClassOf [ a ns1:Restriction ;
            ns1:onClass meta:ncname ;
            ns1:onProperty meta:local_name_source ;
            ns1:qualifiedCardinality 1 ],
        [ a ns1:Restriction ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:local_name_value ;
            ns1:qualifiedCardinality 1 ] .

meta:Prefix rdfs:subClassOf [ a ns1:Restriction ;
            ns1:onClass meta:ncname ;
            ns1:onProperty meta:prefix_prefix ;
            ns1:qualifiedCardinality 1 ],
        [ a ns1:Restriction ;
            ns1:onClass meta:uri ;
            ns1:onProperty meta:prefix_reference ;
            ns1:qualifiedCardinality 1 ] .

meta:abstract a ns1:ObjectProperty .

meta:alias a ns1:ObjectProperty .

meta:aliases a ns1:ObjectProperty .

meta:alt_descriptions a ns1:ObjectProperty .

meta:class_uri a ns1:ObjectProperty .

meta:classes a ns1:ObjectProperty .

meta:close_mappings a ns1:ObjectProperty .

meta:comments a ns1:ObjectProperty .

meta:default_curi_maps a ns1:ObjectProperty .

meta:default_prefix a ns1:ObjectProperty .

meta:default_range a ns1:ObjectProperty .

meta:definition_uri a ns1:ObjectProperty .

meta:deprecated a ns1:ObjectProperty .

meta:deprecated_element_has_exact_replacement a ns1:ObjectProperty .

meta:deprecated_element_has_possible_replacement a ns1:ObjectProperty .

meta:emit_prefixes a ns1:ObjectProperty .

meta:exact_mappings a ns1:ObjectProperty .

meta:examples a ns1:ObjectProperty .

meta:from_schema a ns1:ObjectProperty .

meta:generation_date a ns1:ObjectProperty .

meta:id a ns1:ObjectProperty .

meta:id_prefixes a ns1:ObjectProperty .

meta:imported_from a ns1:ObjectProperty .

meta:imports a ns1:ObjectProperty .

meta:in_subset a ns1:ObjectProperty .

meta:inverse a ns1:ObjectProperty .

meta:is_class_field a ns1:ObjectProperty .

meta:is_usage_slot a ns1:ObjectProperty .

meta:license a ns1:ObjectProperty .

meta:local_name_source a ns1:ObjectProperty .

meta:local_name_value a ns1:ObjectProperty .

meta:local_names a ns1:ObjectProperty .

meta:mappings a ns1:ObjectProperty .

meta:metamodel_version a ns1:ObjectProperty .

meta:mixin a ns1:ObjectProperty .

meta:name a ns1:ObjectProperty .

meta:notes a ns1:ObjectProperty .

meta:owner a ns1:ObjectProperty .

meta:prefix_prefix a ns1:ObjectProperty .

meta:prefix_reference a ns1:ObjectProperty .

meta:prefixes a ns1:ObjectProperty .

meta:related_mappings a ns1:ObjectProperty .

meta:see_also a ns1:ObjectProperty .

meta:singular_name a ns1:ObjectProperty .

meta:slot_uri a ns1:ObjectProperty .

meta:slot_usage a ns1:ObjectProperty .

meta:source_file a ns1:ObjectProperty .

meta:source_file_date a ns1:ObjectProperty .

meta:source_file_size a ns1:ObjectProperty .

meta:subclass_of a ns1:ObjectProperty .

meta:subproperty_of a ns1:ObjectProperty .

meta:subsets a ns1:ObjectProperty .

meta:symmetric a ns1:ObjectProperty .

meta:title a ns1:ObjectProperty .

meta:todos a ns1:ObjectProperty .

meta:typeof a ns1:ObjectProperty .

meta:types a ns1:ObjectProperty .

meta:union_of a ns1:ObjectProperty .

meta:value a ns1:ObjectProperty .

meta:values_from a ns1:ObjectProperty .

meta:version a ns1:ObjectProperty .

meta:slots a ns1:ObjectProperty .

meta:TypeDefinition rdfs:subClassOf [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:TypeDefinition ;
            ns1:onProperty meta:typeof ] .

meta:apply_to a ns1:ObjectProperty .

meta:description a ns1:ObjectProperty .

meta:is_a a ns1:ObjectProperty .

meta:mixins a ns1:ObjectProperty .

meta:Definition rdfs:subClassOf [ a ns1:Restriction ;
            ns1:allValuesFrom meta:uriorcurie ;
            ns1:onProperty meta:values_from ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:Definition ;
            ns1:onProperty meta:mixins ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:Definition ;
            ns1:onProperty meta:apply_to ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:Definition ;
            ns1:onProperty meta:is_a ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:boolean ;
            ns1:onProperty meta:abstract ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:boolean ;
            ns1:onProperty meta:mixin ] .

meta:ClassDefinition rdfs:subClassOf [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:uriorcurie ;
            ns1:onProperty meta:subclass_of ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:ClassDefinition ;
            ns1:onProperty meta:mixins ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:ClassDefinition ;
            ns1:onProperty meta:apply_to ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:SlotDefinition ;
            ns1:onProperty meta:slots ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:SlotDefinition ;
            ns1:onProperty meta:slot_usage ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:uriorcurie ;
            ns1:onProperty meta:class_uri ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:ClassDefinition ;
            ns1:onProperty meta:is_a ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:ClassDefinition ;
            ns1:onProperty meta:union_of ] .

meta:SlotDefinition rdfs:subClassOf [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:uriorcurie ;
            ns1:onProperty meta:subproperty_of ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:uriorcurie ;
            ns1:onProperty meta:slot_uri ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:SlotDefinition ;
            ns1:onProperty meta:mixins ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:SlotDefinition ;
            ns1:onProperty meta:inverse ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:SlotDefinition ;
            ns1:onProperty meta:is_a ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:singular_name ],
        [ a ns1:Restriction ;
            ns1:allValuesFrom meta:SlotDefinition ;
            ns1:onProperty meta:apply_to ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:Definition ;
            ns1:onProperty meta:owner ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:boolean ;
            ns1:onProperty meta:is_class_field ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:string ;
            ns1:onProperty meta:alias ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:boolean ;
            ns1:onProperty meta:symmetric ],
        [ a ns1:Restriction ;
            ns1:maxQualifiedCardinality 1 ;
            ns1:onClass meta:boolean ;
            ns1:onProperty meta:is_usage_slot ] .




Failure
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/cjm/repos/biolinkml/tests/test_base/test_metamodel.py", line 33, in test_meta_owl_schema
    self.single_file_generator('owl', OwlSchemaGenerator, comparator=GeneratorTestCase.rdf_comparator)
  File "/Users/cjm/repos/biolinkml/tests/utils/generator_utils.py", line 152, in single_file_generator
    comparator(self, old_data, new_data, new_file, message, filtr=filtr)
  File "/Users/cjm/repos/biolinkml/tests/utils/generator_utils.py", line 94, in rdf_comparator
    self.fail("RDF file mismatch" if not msg else msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: 
***** Expected output is in meta.owl and actual is in tests/target/meta.owl *****
***** Remove meta.owl and re-run to update

```

**Comment by cmungall** [comment]
The new one is the correct one but I don't know how to replace

**Comment by hsolbrig** [comment]
The new framework has eliminated this problem (I hope)
