### ISSUE TITLE
Strange error during Python installation of BIolinkMG?

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolinkml#28]
In a context in which **BiolinkMG** is a Python module dependency (as of today, 2019-06-27), the attempted installation of the requirement gives the following error:

```
    reading manifest file 'BiolinkMG.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\cygwin64\tmp\pip-install-tgedfe0t\BiolinkMG\setup.py", line 64, in <module>
        "Programming Language :: Python :: 3.7",
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
        self.run_command('egg_info')
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 296, in run
        self.find_sources()
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 303, in find_sources
        mm.run()
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 534, in run
        self.add_defaults()
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 578, in add_defaults
        self.read_manifest()
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\sdist.py", line 199, in read_manifest
        self.filelist.append(line)
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\egg_info.py", line 476, in append
        path = convert_path(item)
      File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\distutils\util.py", line 110, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/Users/solbrig/git/biolink-continuous/biolink-model/BiolinkMG.egg-info/PKG-INFO' cannot be absolute
```

**Comment by hsolbrig** [comment]
BiolinkMG is no longer current - we've switched to biolinkml.  That said, if needs be we can find that nasty little absolute path and fix it if work will continue with BiolinkMG

**Comment by RichardBruskiewich** [comment]
Thanks Harold for your reply to this. I'll need to check why BiolinkMG is still used within the Translator Workflow 2 module as a dependency... maybe it is an legacy artefact.

**Comment by hsolbrig** [comment]
Ok, although Chris reminded me that BiolinkMG was the only place to get datamodel.py -- but the copy in the distro is pretty dated
