### ISSUE TITLE
Using reserved words such as 'null' generates undecipherable stack traces

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#346]
if I use the keyword `null` as a slot name:

```yaml
id: http://w3id.org/test
description: test
imports:
- biolinkml:types
prefixes:
  biolinkml: https://w3id.org/biolink/biolinkml/
  test: https://w3id.org/mixs/
default_prefix: test
slots:
  null: {}
  
classes:
  core:
    slots:
    - null
```

and try and use any generator I get stack traces that don't identify the root cause. this can be hard to debug in large schemas

```bash
$ gen-py-classes ~/tmp/bad.yaml 
/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/__init__.py:158: UserWarning: Some URL processing will fail with python 3.7.5 or earlier.  Current version: sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
  warn(f"Some URL processing will fail with python 3.7.5 or earlier.  Current version: {sys.version_info}")
Traceback (most recent call last):
  File "/Users/cjm/repos/mixs-demo/venv/bin/gen-py-classes", line 11, in <module>
    sys.exit(cli())
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/generators/pythongen.py", line 881, in cli
    print(PythonGenerator(yamlfile, emit_metadata=head, gen_meta=genmeta, gen_classvars=classvars, gen_slots=slots,  **args).serialize(emit_metadata=head, **args))
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/generators/pythongen.py", line 35, in __init__
    super().__init__(schema, format, **kwargs)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/generator.py", line 91, in __init__
    source_file_date=self.source_file_date, source_file_size=self.source_file_size)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/schemaloader.py", line 52, in __init__
    source_file_size=source_file_size)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/rawloader.py", line 78, in load_raw_schema
    emit_metadata=emit_metadata)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/rawloader.py", line 150, in load_raw_schema
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/rawloader.py", line 150, in <dictcomp>
    for sname, sdef in {k: SchemaDefinition(name=k, **v) for k, v in schemadefs.items()}.items():
  File "<string>", line 48, in __init__
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/meta.py", line 390, in __post_init__
    self._normalize_inlined_slot(slot_name="slots", slot_type=SlotDefinition, key_name="name", inlined_as_list=None, keyed=True)
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/utils/yamlutils.py", line 129, in _normalize_inlined_slot
    cook_a_slot(slot_type(**value_copy))
  File "<string>", line 66, in __init__
  File "/Users/cjm/repos/mixs-demo/venv/lib/python3.7/site-packages/biolinkml/meta.py", line 641, in __post_init__
    raise ValueError("name must be supplied")
ValueError: name must be supplied
```

**Comment by cmungall** [comment]
also on reserved words

we don't place constraints on slot names such as forcing them to start with an alphabetic character, so if we have this:

```yaml
id: http://w3id.org/test
description: test
imports:
- biolinkml:types
prefixes:
  biolinkml: https://w3id.org/biolink/biolinkml/
  test: https://w3id.org/mixs/
default_prefix: test
slots:
  3prime: {}
  
classes:
  core:
    slots:
    - 3prime
```

it makes invalid python:

```python
@dataclass
class Core(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = TEST.Core
    class_class_curie: ClassVar[str] = "test:Core"
    class_name: ClassVar[str] = "core"
    class_model_uri: ClassVar[URIRef] = TEST.Core

    3prime: Optional[str] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.3prime is not None and not isinstance(self.3prime, str):
            self.3prime = str(self.3prime)

        super().__post_init__(**kwargs)

```
